--PROGRAMANDO UN STORED PROCEDURE
--VA A RECIBIR COMO PÁRAMETRO
--EL NOMBRE DEL COLABORADOR
USE SEMINARIO;
DELIMITER ##
DROP PROCEDURE IF EXISTS USPCOLABORADORINSCRITOS ##
CREATE PROCEDURE USPCOLABORADORINSCRITOS(in nom nvarchar(50))
BEGIN
 SELECT C.ID_COLABORADOR,C.NOMBRE,
        COUNT(CL.ID_COLABORADOR) AS INSCRITOS
 FROM COLABORADORES AS C INNER JOIN CATALOGO_LISTAS AS CL
      ON C.ID_COLABORADOR=CL.ID_COLABORADOR
 WHERE
     C.NOMBRE=nom
     GROUP BY C.ID_COLABORADOR;
END ##
DELIMITER ;

USE SEMINARIO;
CALL USPCOLABORADORINSCRITOS('ARELY');

